infra:
  oauth2:
    authorization-server:
      oauth2-client:
        oidc-login-enabled: false
      create-jdbc-schema: false
      token:
        jwt:
          rsa:
            private-key: "aaa"


  caching:
    provider: memory
    redis:
      regions:
        default:
          url: redis://localhost:6379/1
          serializer: kotlin-protobuf
server:
  port: 8089
  forward-headers-strategy: framework


logging:
  level:
    root: warn
    com.labijie: debug
    org:
      springframework:
        security:
          web: trace

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver




