infra:
  oauth2:
  caching:
    provider: redis
    redis:
      regions:
        default:
          url: redis://localhost:6379/1
          serializer: kotlin-protobuf
server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver


