infra:
  oauth2:

  caching:
    provider: memory
    redis:
      regions:
        default:
          url: redis://localhost:6379/1
          serializer: kotlin-protobuf
server:
  port: 8088
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    oauth2:
      authorizationserver:
        issuer: https://test.api
      client:
        oidc-login-enabled: true
        oidc-login:
          google:
            audience-set:
          apple:
            audience-set:
        registration:
          apple:
            client-id: ai.ciney.videobot
            team-id: 78L4772BQR
            key-id: G92XUZNXMB
            private-rsa-key: AuthKey_G92XUZNXMB.p8
          google:
            client-id: XXXX
            client-secret: XXXX




