infra:
  oauth2:
    authorization-service: jdbc
    create-jdbc-schema: true
server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

