infra:
  oauth2:

  caching:
    provider: memory
    redis:
      regions:
        default:
          url: redis://localhost:6379/1
          serializer: kotlin-protobuf
server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    oauth2:
      authorizationserver:
        issuer: https://test.api
      client:
        oidc-login-enabled: true
        oidc-login:
          google:
            audience-set:
          apple:
            audience-set:




